version: '3'

services:  
  backend:
    container_name: backend
    hostname: backend

    build: ./backend
    ports:
    - "8000:8000"
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: frontend
    hostname: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - PORT=3000
      - BACK_END_SERVICE_HOST=backend:8000