version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    hostname: frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - PORT=3000
      - BACK_END_SERVICE_HOST=backend:8000
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
